[package]
name = "say-my-name"
version = "0.1.0"
authors = ["Kevin Cunningham <kevin@kevincunningham.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
